version: "3.9"

services:
  db:
    container_name: "db"
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge