version: "3.9"

services:
  fastapi_ylab:
    container_name: fastapi_ylab
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_ylab:5432/${POSTGRES_DB}"
      CACHE_URL: "redis://redis_ylab:6379/0"
    entrypoint: sh -c "alembic upgrade head && uvicorn main:app --host fastapi_ylab --port 8000"
    volumes:
      - shared-volume:/app/generated_files
    networks:
      - ylab_network
    ports:
      - "8000:8000"
    depends_on:
      postgres_ylab:
        condition: service_healthy
      redis_ylab:
        condition: service_healthy

  redis_ylab:
    container_name: redis_ylab
    image: redis:7.0.12-alpine
    ports:
      - "6379:6379"
    networks:
      - ylab_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3


  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${PGUSER}"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ylab -h 0.0.0.0 -p 5432"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

networks:
  ylab_network:
    name: ylab_network
volumes:
  postgres_data:
  shared-volume:

